---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-nfs
spec:
  containers:
    - image: nginx:latest
      name: nginx-nfs-csi
      command:
        - "/bin/bash"
        - "-c"
        - set -euo pipefail; while true; do echo $(date) >> /mnt/nfs/outfile; sleep 1; done
      volumeMounts:
        - name: goodtimes
          mountPath: "/mnt/nfs"
          readOnly: false
  volumes:
    - name: goodtimes
      persistentVolumeClaim:
        claimName: goodtimes-pvc